### ISSUE TITLE
[BUG] 4002 error in Adobe Appearance Integrity Report for digital signature

### ISSUE THREAD

**Issue by falgonua** [unidoc/unipdf#369]
## Description
When we create any digital signature on document Adobe Appearance Integrity Report always show 4002 error for digital signature.
![image](https://user-images.githubusercontent.com/38418746/84114161-884d2580-aa34-11ea-8824-baef06af3862.png)

## Expected Behavior
Add digital signature without any errors from Adobe Appearance Integrity Report

## Actual Behavior
1. Add any digital signature
2. Open signature tab and click to "Click to view this version
![image](https://user-images.githubusercontent.com/38418746/84114384-f2fe6100-aa34-11ea-88ab-50c86e38c4fe.png)
3. Click on view report button
![image](https://user-images.githubusercontent.com/38418746/84114456-0f9a9900-aa35-11ea-9350-37b610a99153.png)
![image](https://user-images.githubusercontent.com/38418746/84114480-175a3d80-aa35-11ea-8b34-4bd890272116.png)

**Comment by gunnsth** [comment]
@falgonua Can you submit a self-contained, reproducible code that we can run to get the same result? And also example PDF files.  Can submit to us via email if you prefer.

**Comment by falgonua** [comment]
@gunnsth, sure. I send via email to support@unidoc.io

**Comment by gunnsth** [comment]
@falgonua Can you confirm that this has been fixed in the newest releases?

**Comment by falgonua** [comment]
@gunnsth Currently we updated to 3.9.0. The problem still exists. We are planning to update to the latest version in a few weeks.

**Comment by gunnsth** [comment]
@falgonua Have you managed to test this yet?

**Comment by gunnsth** [comment]
@falgonua Look forward to an update on this.

**Comment by falgonua** [comment]
@gunnsth hi. Checked on the v3.26.1 version. The bug was fixed. Thanks a lot.
