### ISSUE TITLE
[BUG] A rotated PDF cannot be rotated again

### ISSUE THREAD

**Issue by leep-frog** [unidoc/unipdf#475]
## Description
A file can only be rotated once

## Expected Behavior
Upon a second rotation attempt, I expected the pdf to either be rotated again or for an error to be returned.

## Actual Behavior
Using [this example](https://unidoc.io/unipdf-examples/pdf-page-rotate/) on the same file twice in a row only changes the file once:

```
go run pdf_rotate.go simple.pdf simple.pdf 90 # rotates the file by 90 degrees successfully
go run pdf_rotate.go simple.pdf simple.pdf 180 # nothing happens, and no error is returned
```

**Comment by gunnsth** [comment]
The problem was with the example as it had hardcoded 90 degrees, fixed in https://github.com/unidoc/unipdf-examples/pull/172

**Comment by leep-frog** [comment]
The issue is still not fixed.  Try rotating the pdf twice (one 90 degrees and once 180 degrees) and the second rotation still won't work.  I don't think it's merely an issue with the example.  The underlying implementation appears to be unable to rotate an already rotated image.

**Comment by gunnsth** [comment]
It sets the rotation flag, so if you set it to 90 it goes to 90, if you set it to 180.  If you want it to add to the current rotation setting, then you need to simply get the current rotation and add to it.  The Rotate field goes in 90 degree increments.

**Comment by leep-frog** [comment]
Right.  I basically do the following things though:
```
set rotation 90 myPdf.pdf # works
set rotation 180 myPdf.pdf # does not work
```
It seems like there is an issue when the rotation is already set.
